# Commands to bootstrap the environment before each job is run. This is here for
# reference but we don't need to bother with it anymore now that we use a
# Makefile.
before_script:

# Test Job: Run the unit tests.
unit_tests:
    script:
        - make unit_tests

# Test Job: Run the functional tests.
functional_tests:
    script:
        - make functional_tests

# Test Job: Check the coding standards of the source code.
coding_standards:
    script:
        - make functional_tests

# Check PHP dependencies for known security vulnerabilities.
check_security:
    script:
        - make security_check

# Deployment Job: If all tests pass and this is branch master, then deploy the application.
ansible_playbook:
    type: deploy
    only: [ master ]
    script:
        - make deploy
